linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    - gofumpt
    - varnamelen
    - testpackage
    - exhaustruct
    - nonamedreturns
    - exhaustivestruct
    - exhaustive
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - goerr113
