run:
  allow-parallel-runners: true
  go: '1.22'

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - nonamedreturns
    - exhaustruct
    - exhaustive
    - varnamelen
    - depguard
    - intrange
    - ireturn
    - gofumpt

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - funlen
